FROM haxe:latest AS haxebuild

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY . /app

RUN haxelib git weblink https://github.com/PXshadow/weblink 
RUN haxelib install hashlink 
RUN haxelib git haxeui-core https://github.com/haxeui/haxeui-core
RUN haxelib git haxeui-html5 https://github.com/haxeui/haxeui-html5
RUN haxe build.hxml

FROM haxe:latest AS releasebuild

# ## Install hashlink deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    libmbedtls-dev \
    libopenal-dev \
    libpng-dev \
    libsdl2-dev \
    libturbojpeg-dev \
    libuv1-dev \
    libvorbis-dev \
    libsqlite3-dev \
    libglu1-mesa-dev \
    libgl-dev \
    make

## pull and build hashlink
WORKDIR /hashlink
RUN git clone https://github.com/HaxeFoundation/hashlink .
RUN make && make install

## clean up
RUN cd /
RUN rm -rf /hashlink

## build linux release
WORKDIR /release
COPY --from=haxebuild /app/dist /release
RUN gcc -o RFIDTriggerServer out/RFIDTriggerServer.c -Iout /usr/local/lib/*.hdll -lhl -luv

## clean up
RUN rm -rf /release/out

# ---- Exporter stage (tiny) ----
FROM alpine:latest
WORKDIR /
# copy build results into /output inside the runtime container
COPY --from=releasebuild /release /output

# Copy output into mounted volume when container runs
CMD sh -c "mkdir -p /release && cp -r /output/. /release/ && echo '✅ Artifacts copied to /release'"